### ISSUE TITLE
Make diff HTML file name configurable

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-checker#10]
Currently the output file in HTML format is fixed to `diffHTML.html`. It would be nice to be able to configure this as a user of the tool at the time of the check.

**Comment by Timmimim** [comment]
Added `.outFileName` attribute for `config` Object, and support in code, as well as 2 Tests to varify correct results for manual setting and default.
https://github.com/Timmimim/erc-checker/commit/12e1be1e48a4595f385953d305a8dff1ed5423a1

**Comment by nuest** [comment]
Please also add documentation in the README.

**Comment by Timmimim** [comment]
Done. :)
https://github.com/Timmimim/erc-checker/commit/169a4559bbb4cd6e2fb1a65e86789cda9c515ee9
