### ISSUE TITLE
Use empty list if no images, and do only add content to display if there is any

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-checker#13]
Currently, if there is an error (not a failed check), the created object is

```
checkSuccessful:false
display:Object {diff: null}
end:1510999723270
errors:Array(1) ["Error: ENOENT: no such file or directory, stat '/t…"]
images:null
start:1510999723270
```

- [x] use an _empty list_ for `images` (`[]`) instead of `null` @Timmimim 
- [x] use an empty object (`{}`) for display if `diff` is `null` @Timmimim 
- [ ] remove special handling in muncher @nuest

**Comment by Timmimim** [comment]
Changed parameter initializations and commited changes.
https://github.com/Timmimim/erc-checker/commit/09ca03b051431d1d6c6701293f303941f8a9435d
