### ISSUE TITLE
Re-check all usages of .map function

### ISSUE THREAD

**Issue by nuest** [o2r-project/erc-checker#15]
The function `array.map(..)` is wrongly used to iterate over an array, e.g. in `runBlinkDiff`. Make sure that in the function provided to map, `return` is called and the result is assigned, e.g. `result = array.map(function(element) return element);`
If iterating, then use `array.forEach()`.

**Comment by Timmimim** [comment]
Double-checked usages and commited changes.
https://github.com/Timmimim/erc-checker/commit/83c759de47d3f3da676b27590960f328e59ac33c
